### ISSUE TITLE
likelihood는 보통 가능도나 우도로 번역되는데 이는 번역에 적용하지 않나요?

### ISSUE THREAD

**Issue by presentY1897** [d2l-ai/d2l-ko#60]
일반적으로 통계학에서는 likelihood를 가능도나 우도로 번역합니다. 다만, 해당 내용이 용어표에도 없고 실제 문서상에서도 원문 그대로 사용되는 것 같습니다. 이 단어에 대한 토의가 있어 정해진 내용이 있을까요?

**Comment by muhyun** [comment]
좋은 의견 감사드립니다. 지금 0.7.1 버전에 대한 번역을 진행 중이고, 용어표에 대한 전반적인 수정도 함께 할 예정입니다. 071 폴더에 용어표를 새로 업데이트하면서 진행하는데, 지속적인 의견 부탁드립니다.
