### ISSUE TITLE
번역에 기여를 하고 싶습니다.

### ISSUE THREAD

**Issue by Gumball12** [d2l-ai/d2l-ko#63]
안녕하세요, 컴퓨터를 공부하고 있는 학생입니다.

d2l-en 번역에 기여를 하고 싶어 이슈를 남기게 되었습니다.
버전 0.7.1에 맞추어 빌드 및 번역을 진행하기 위해 최신 버전의 d2l-en를 cloning 후,
d2l-ko를 forking한 뒤 새로이 working directory를 만들어 작업을 진행하고 있습니다.

[Preface](https://github.com/Gumball12/d2l-ko/blob/master/071_2/chapter_preface/index.md), [Installation](https://github.com/Gumball12/d2l-ko/blob/master/071_2/chapter_installation/index.md), [Notation](https://github.com/Gumball12/d2l-ko/blob/master/071_2/chapter_notation/index.md) 및 [Contributing to This Book](https://github.com/Gumball12/d2l-ko/blob/master/071_2/chapter_appendix-tools-for-deep-learning/contributing.md) 초벌 번역을 마친 상태이며, 현재 [Introduction](https://github.com/Gumball12/d2l-ko/blob/master/071_2/chapter_introduction/index.md) 번역을 진행중에 있습니다.

학부연구생 신분이지만, 번역에 기여를 하고 싶습니다. 기초적인 git을 다룰 수 있으며, d2l-ko contribute guideline 및 building process에 대한 이해를 마쳤습니다. 시간이 나는 대로 (특히 주말) 번역을 진행할 예정입니다.

피드백 기다리겠습니다. 감사합니다.

**Comment by muhyun** [comment]
네 관심을 보여주셔서 감사합니다. 종이책으로 출판할 예정도 있기 때문에 주 번역은 저희팀에서 할 계획이나 번역에 대한 피드백을 주시는 형태로 기여는 가능합니다. 아직 영문 버전에 대한 완료가 되지 않아서 한글 번역을 시작하지 않고 있는 상태입니다. 번역이 시작되면 피드백 형태로 참여를 부탁드립니다.

감사합니다.

**Comment by Gumball12** [comment]
알겠습니다. 빠른 피드백 감사합니다!..
